steps:
konteynır imajını g-cloudedan çek
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/myapp', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/myapp']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'myapp', '--image', \
         'gcr.io/$PROJECT_ID/myapp', '--region', \
         'us-central1', '--platform', 'managed','--port','80']
images:
- gcr.io/$PROJECT_ID/myapp
